### ISSUE TITLE
Main.cpp compile error using opencv 3.2.0

### ISSUE THREAD

**Issue by jamesthesken** [Xonxt/frst#1]
frst.h:80:39: error: no matching function for call to 'std::exception::exception(const char [14])'
   throw std::exception("invalid mode!");

**Comment by jamesthesken** [comment]
Will work on this

**Comment by Xonxt** [comment]
> no matching function for call to 'std::exception'

My bad. It seems that an `std::exception` function that takes `const char` as an argument is a feature of MSVS and not defined by C++ standard. You just have to remove the `char` argument or use some other way to notify the user that he's calling the `frst` function with an incorrect mode.

**Comment by jamesthesken** [comment]
Thank you! Will let you know what happens.

**Edit**: Might be more difficult to check if any fixes work considering I am using 3.2.0. I deleted the std::exception lines. The compilation is throwing mass amounts of undefined references to cv now

**Comment by Xonxt** [comment]
> Might be more difficult to check if any fixes work considering I am using 3.2.0. I deleted the std::exception lines. The compilation is throwing mass amounts of undefined references to cv now

Sorry for not answering, I haven't seen your edit.
I'm using the 3.2.0 at the time as well and removing the `std::exception` line or simply replacing it with a `return` statement works fine for me. What IDE are you using?

**Comment by jamesthesken** [comment]
> What IDE are you using?

I'm using Eclipse right now.

**Comment by Xonxt** [comment]
> I'm using Eclipse right now.

Honestly, I've rarely heard of Eclipse being a viable option for C++ development.
Please, check that OpenCV is included into your project properly. Try running a simple openCV project to check that it even works. Otherwise, I'd suggest a different IDE. The newest Visual Studio that I'm using is available for free as a "community version".
